### ISSUE TITLE
Installing from master currently fails

### ISSUE THREAD

**Issue by buzacott** [josephguillaume/hydromad#166]
# Issue: Installing from master currently fails

## Issue summary:

`devtools::install_github()` and `devtools::install()` fails from the master clone due to missing _hydromad_simhyd_sim. This is because there are no R/RcppExports.R and no src/RcppExports.cpp in the repo as they were removed in #53 

## Expected Behavior

Package should install without error
## Current Behavior

Package fails to install

## Possible Solution

Running Rcpp::compileAttributes() and then running devtools::install() installs without error.

Add the files back is the obvious solution, but I'm not sure how this would interfere with the CI. Have an action to  run Rcpp::compileAttributes() on push and maintain them in the .gitignore?

## Steps to Reproduce (for bugs)
devtools::install_github('josephguillaume/hydromad')

## Context

#158 when issue was reported

## Your Environment

macOS/ubuntu18

**Comment by josephguillaume** [comment]
RStudio automatically runs compileAttributes on build, which is why I hadn't considered it an issue. It's a bit annoying that install_github does not. 
Considering we now have several other autogenerated files in the repo, there's no harm in adding them back in.

Would you be willing to add a compileAttributes call to https://github.com/josephguillaume/hydromad/blob/master/.github/workflows/roxygenise.yml ?

**Comment by buzacott** [comment]
I tried `devtools::install_github('josephguillaume/hydromad')` and the issue still exists.

I think the workflow isn't committing the necessary files to the repo because the trigger isn't right.

e.g. compare:

https://github.com/josephguillaume/hydromad/blob/bb341f7dce9b4c27879bbd54368c6046ee841e12/.github/workflows/roxygenise.yml#L1-L5

to

https://github.com/josephguillaume/hydromad/blob/bb341f7dce9b4c27879bbd54368c6046ee841e12/.github/workflows/render-readme.yaml#L1-L6

Not sure what the correct action is that should trigger it, but I'm guessing it should be on the pull request?

**Comment by josephguillaume** [comment]
Thanks for testing, @buzacott.
@mortisflux - sorry to bother you. Do you remember why the roxygenise trigger is on issue_comment from #153 ?

**Comment by mortisflux** [comment]
Hi @josephguillaume apologies for not replying earlier, this account is linked to another email that I haven't checked in a while.

`issue_comment` aren't just issues, they're also pull requests: [https://stackoverflow.com/questions/59778589/github-action-receive-event-when-comment-added-to-pr](https://stackoverflow.com/questions/59778589/github-action-receive-event-when-comment-added-to-pr). I think roxygenise was added here so that it would trigger during a PR.

**Comment by buzacott** [comment]
This issue is still lingering but has finally been solved as you can see here: https://github.com/buzacott/hydromad/tree/ghroxy

Now the question is if we want to manually invoke the workflow using the /document command on relevant pull requests, which is also how it is shown in https://github.com/r-lib/actions/blob/master/examples/pr-commands.yaml#L1-L7 e.g. 

```
on:
  issue_comment:
    types: [created]
```
which then needs to be followed up a comment on the PR `/document`

or do we want the action to happen automatically when a pull request is merged into master e.g.

```
on:
  push:
    branches: 
      - master
```

**Comment by buzacott** [comment]
Can also confirm that installing isn't a problem from the branch `remotes::install_github("buzacott/hydromad@ghroxy")`
