### ISSUE TITLE
Error when running fitBySCE

### ISSUE THREAD

**Issue by HalfEatenPie** [josephguillaume/hydromad#30]
Hello,

Thanks for maintaining Hydromad.  

Recently ran into an issue where the following error occurs when running fitBySCE:
```
Error in seq.default(finitelower[i], finiteupper[i], length = nPOINTS -  : 
  'from' must be a finite number
```

My calls are:
```
model <- hydromad(tsdata, sma = "gr4j", routing = "gr4jrouting", trasnformed = FALSE)
hydromad.options(warmup = 366)
hydromad.options(objective = ~hmadstat("r.squared")(Q, X))
hydromad.options(polish = FALSE)
hydromad.options(trace = TRUE)
hydromad.options(normalise = FALSE)
hydromodel <- fitBySCE(model, control = list(ncomplex = 5))
```

Nothing defined for X1, x2, x3, and x4.  

Any suggestions or idea as to why this error occured?

Thanks!

**Comment by josephguillaume** [comment]
I assume the issue was solved?
For general user questions, see: http://groups.google.com/group/hydromad-users

Reproducible examples are needed to debug possible problems with hydromad. In this case, there's a typo in "transformed", but there is otherwise insufficient information to know what would have caused the error.
