### ISSUE TITLE
README rendering

### ISSUE THREAD

**Issue by josephguillaume** [josephguillaume/hydromad#77]
@WillemVervoort - looks like I accepted the PR prematurely :-P

Installation of hydromad seems to fail due to missing dependencies
https://github.com/josephguillaume/hydromad/runs/817246064

@mortisflux - do you see any obvious problem here?
https://github.com/josephguillaume/hydromad/blob/master/.github/workflows/render-readme.yaml

**Comment by mortisflux** [comment]
Does hydromad have to be installed/compiled before running the .yaml file? I think RMarkdown should be able to render the .Rmd without a full installation of hydromad. I'd try getting rid of:

```
      - name: Install hydromad
        run: Rscript -e 'install.packages("hydromad", repos = "http://hydromad.catchment.org")'
```

**Comment by WillemVervoort** [comment]
I put that in because I thought I needed that to convert the Rmd to md.
Happy to remove.
Willem

**Comment by WillemVervoort** [comment]
New pull request? or do you reopen?
Willem

**Comment by josephguillaume** [comment]
> Does hydromad have to be installed/compiled before running the .yaml file?

Hydromad is needed to run the example - if we don't run the example dynamically, then we don't need the .yaml file at all I think.

The error is that the dependencies aren't installed, so the obvious fix is to install them I suppose?

@WillemVervoort - It would be a new PR because i've merged the previous one already

**Comment by mortisflux** [comment]
The `standard_R_ci.yaml` file should have some of the code for downloading dependencies. That can be copied, pasted, and substituted with the required packages and installed run prior to the hydromad installation step.

**Comment by WillemVervoort** [comment]
> 
> 
> The `standard_R_ci.yaml` file should have some of the code for downloading dependencies. That can be copied, pasted, and substituted with the required packages and installed run prior to the hydromad installation step.

Can you explain this a bit more. I think I don't totally understand what I need to change on my end. Should I include standard_R_ci_yaml in my branch and adjust, or do you think if I remove the hydromad installation step from the readme yaml it will resolve the issue  because the standard_R_ci_yaml will cover that?
My branch does not have standard_R_ci_yaml, should I add?

**Comment by josephguillaume** [comment]
I think it's an easy fix, and I just noticed there's things I want to change in standard_R_ci.yaml, so I'll have a go now.

**Comment by WillemVervoort** [comment]
OK, I am struggling a bit because I updated my fork with your (@josephguillaume ) repository, but now I am not sure whether it is now a mess because you are still working on the lint and styler problems. Maybe if someone can talk me through this to make sure I am doing it correctly? maybe @mortisflux? or @josephguillaume

**Comment by WillemVervoort** [comment]
Also, my test suggests it clearly needs to install hydromad in the render readme.
However, I now also question whether we need to run the yaml. If I change the README.rmd and commit and push using bash, git warns me that README.md is out of date and that I need to rerender README.md

**Comment by WillemVervoort** [comment]
Sorry, no progress, even with including your suggestions:
##[error]Error: (converted from warning) packages ‘ppso’, ‘dream’ are not available (for R version 4.0.2)
How do I get rid of ppso and dream?

**Comment by mortisflux** [comment]
@WillemVervoort, to answer your questions  

> OK, I am struggling a bit because I updated my fork with your (@josephguillaume ) repository, but now I am not sure whether it is now a mess because you are still working on the lint and styler problems. Maybe if someone can talk me through this to make sure I am doing it correctly?

The updated fork looks good to me!

> Also, my test suggests it clearly needs to install hydromad in the render readme.

I agree, I just saw the output of your test [here](https://github.com/WillemVervoort/hydromad/runs/821121821?check_suite_focus=true).

>> The standard_R_ci.yaml file should have some of the code for downloading dependencies. That can be copied, pasted, and substituted with the required packages and installed run prior to the hydromad installation step.

> Can you explain this a bit more. I think I don't totally understand what I need to change on my end. Should I include standard_R_ci_yaml in my branch and adjust?

I think you've made the majority of the changes needed to make this action work. You're now having the same error I recall from working on standard_r_ci.yaml: dream and ppso couldn't be installed using remotes::install_deps() so I appended the "Install dependencies" part of the script to include:

```
      - name: Install dependencies
        run: |
          remotes::install_github("TillF/ppso")
          remotes::install_url("http://download.r-forge.r-project.org/src/contrib/dream_0.4-2.tar.gz")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
```

If you give this a go it should hopefully solve the particular error message you're getting at the moment. Please note that the ppso/dream installations need to come before the rest of the dependencies, otherwise that step in the action will fail!

**Comment by josephguillaume** [comment]
My latest commit to that PR should fix it - unless you've experienced otherwise, using `remotes::install_deps()`  instead of `remotes::install_deps(dependencies = TRUE)` should avoid the need for ppso and dream?
